  #######################################################################################
  #######################################################################################
  #######################################################################################
  #####                                                                             #####
  #####                       Savage Alerts 1.0                                     #####
  #####                       Created By Driftay                                    #####
  #####                                                                             #####
  #######################################################################################
  #######################################################################################
  #######################################################################################
#<---------------------->NOTES<---------------------->#
#All Color Codes Can Be Used!
#Refer to: https://wiki.ess3.net/mc/
#<---------------------->NOTES<---------------------->#

############################################################
# +------------------------------------------------------+ #
# |                  Faction Messages                    | #
# +------------------------------------------------------+ #
############################################################
Permission-Node: 'savagealerts.reload'
Reloaded-Message: '&f[&bSavage&cAlerts&f] &2Configuration has been successfully reloaded!'
No-Permission: '&f[&bSavage&cAlerts&f] &cYou are not permitted to use &4/savagealerts!'
No-Args: '&f[&bSavage&cAlerts&f] &2Command Not Found! Try &4/savagealerts reload&2!'

FactionMessagesEnabled: true

FactionMemberJoinedMessage: '&2&l%faction% Alert&f: &b&l%player% &2has just logged in!'
FactionMemberLeftMessage: '&2&l%faction% Alert&f: &b&l%player% &chas just logged out!'


  #######################################################################################
  #######################################################################################
  #######################################################################################
  #####                                                                             #####
  #####                       Savage Alerts 1.0                                     #####
  #####                       Created By Driftay                                    #####
  #####                                                                             #####
  #######################################################################################
  #######################################################################################
  #######################################################################################